### ISSUE TITLE
RSS link returns 404

### ISSUE THREAD

**Issue by Minoru** [hatsunearu/hatsunearu.github.io#1]
Hi! The link in the footer of your blog leads to https://hatsunearu.github.io/feed.xml, but that URL returns error 404. Can this be fixed somehow?

**Comment by hatsunearu** [comment]
:( I'm not good with Jekyll and web stuff so this might take a while--I kind of suspected that it won't work... I'll try to get it working ASAP! (Before my next blog post...) 

Thanks for letting me know!

**Comment by hatsunearu** [comment]
OK, a46e2fe62ae8880a60105fd4e53e8e1f83127401 should fix this issue. I don't use RSS myself so could you check if your RSS client is happy with it?

**Comment by Minoru** [comment]
Yes, it works now. Thank you for fixing it, @hatsunearu!
